FROM python:3.11-slim

WORKDIR /app

# Copia e instala dependências Python
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copia a aplicação Streamlit e dataset
COPY app.py ./
COPY dataset/ ./dataset

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0"]