version: "2.4"

services:
  programa_c:
    build:
      context: .
      dockerfile: Dockerfile.c
    stdin_open: true
    tty: true
    volumes:
      - ./dataset:/app/dataset
    networks:
      - minha_rede
    cpus: 1.0
    mem_limit: 300m

  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - programa_c
    volumes:
      - ./dataset:/app/dataset
    networks:
      - minha_rede
    cpus: 1.0
    mem_limit: 500m

networks:
  minha_rede:
    driver: bridge
    name: estrutura_dados_minha_rede