version: "3.8"

services:
  programa_c:
    build:
      context: .
      dockerfile: Dockerfile.c
    stdin_open: true
    tty: true
    volumes:
      - ./dataset:/app/dataset
    networks:
      - minha_rede
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 200m

  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - programa_c
    volumes:
      - ./dataset:/app/dataset
    networks:
      - minha_rede
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 600m

networks:
  minha_rede:
    driver: bridge
    name: estrutura_dados_minha_rede
